name: master-build

on:
  push:
  branches:
      - "**"



jobs:
  build-and-test:
  name: Test
  runs-on: ubuntu-latest

steps:
  - name: Clone Repo
    uses: actions/checkout@v2

- name: Install
    working-directory: .
    run: |
    npm install


- name: Install
    working-directory: .
    run: |
    npm test
